[package]
name = "init"
version = "0.0.0"
edition = "2021"

[dependencies]
rustix = { version = "0.38.31", default-features = false, features = ["mount", "std"] }
tokio = { version = "1.36.0", default-features = false, features = ["process", "rt-multi-thread", "sync", "time"] }
